# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 16:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atol', '0002_receipt_retried_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='purchase_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Позиции чека'),
        ),
    ]
